version: "3"

services:
    wichtech-website:
        image: nginx
        container_name: wichtech_website
        ports:
            - 9876:80
        volumes:
            - ./public:/usr/share/nginx/html
